// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace OneTimeDisablerExtension.Commands
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidVSPackageString = "78c53a44-6ca7-4984-a092-8cf5839dfde8";
        public static Guid guidVSPackage = new Guid(guidVSPackageString);

        public const string guidVSPackageCmdSetString = "a84f652b-4f12-40bd-9963-34e553920b4b";
        public static Guid guidVSPackageCmdSet = new Guid(guidVSPackageCmdSetString);

        public const string guidImagesString = "1a9f762f-b166-46de-93a5-5c3c0a09bcb3";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int DisableAndRestartCommandId = 0x0100;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}