// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace OneTimeDisablerExtension
{
    internal sealed partial class Vsix
    {
        public const string Id = "2091baa1-33e2-4d79-bf99-67f83ac7cf2c";
        public const string Name = "OneTimeDisablerExtension";
        public const string Description = @"Easily temporarily disable an extension until the next VS restartExtension to allow the temp";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Destects";
        public const string Tags = "";
    }
}
